### ISSUE TITLE
what is your final KL loss value in your liGAN paper?

### ISSUE THREAD

**Issue by yangxiufengsia** [mattragoza/liGAN#12]
Hi

I obtained over 90% valid percentage of posterior sampling of liGAN, but I got 0% valid percentage from prior sampling of liGAN. 
My final KL loss is around 3, which i think it is already small. 
I want to ask what is your final KL loss in you liGAN paper? since this loss is not reported in your results.
Thank you!

**Comment by mattragoza** [comment]
Hello,

The training plots for our final parameter sweep can be found in this ipython notebook:

https://github.com/mattragoza/ipython-notebooks/blob/master/train_molport_loss_weights.ipynb

The VAE model that was used in the paper is called "gen_e_0.1_1_disc_x_10" in these plots. The final K divergence loss was around 260, which is significantly higher than what you are seeing. Anecdotally, we also tend to see that the prior samples are less useful when the KL divergence is very low, possibly because it is harder to encode complex information in the latent space when it follows a simple Gaussian distribution compared to when it does not.

Are you using the --dkoes_make_mol flag to generate.py when you are generating your molecules? This is a superior bond-adding algorithm to the default method and it may increase your validity.

Best,
Matt

________________________________

**Comment by yangxiufengsia** [comment]
Thanks a lot for your quick reply. I didn't use --dkoes_make_mol this parameter for both prior and posterior sampling.  I will try this method. What is the difference between this one with the default bond adding method?  
I obtained very strange fragments only from prior sampling, which I thought this might because the model doesn't train well (the model is not gaussian, but prior sampling is from gaussian). Also, I found the generated molecules from posterior are not stable, do you have any ideas for generating more stable molecules?
Thank you!

**Comment by mattragoza** [comment]
The default bond adding procedure first uses the OpenBabel functions ConnectTheDots and PerceiveBondOrders, then attempts to connect disconnected fragments and set ring aromaticity afterwards. The improved --dkoes_make_mol procedure has custom implementations of these OpenBabel functions that are more tolerant to making longer bonds and more inclined to respect the atom types (e.g. aromaticity) while creating the bonds.

I suspect that your theory is correct (the latent space does not follow a Gaussian distribution), and we understand that many of the generated molecules are not energetically favorable. Improving the ability to sample from the prior distribution and create more stable molecules are current areas of active research.

**Comment by yangxiufengsia** [comment]
thank you for helping solve my confusions. I want to ask if the dkoes_make_mol is used for obtaining the validity results of prior sampling (no-ligand in figure 2) in your paper (design molecules conditional receptors)? And how different about the validity ratio by using these two different bond adding algorithms (for example, 50% ? prior sampling validity when default is used ) ?

As I understand from your paper (https://arxiv.org/abs/2010.14442), the latent space consists of learned encoded receptor (fixed) and ligand information (gaussian), the latent space is not gaussian then, because the latent space is combined. 
But the ligand latent space does follow gaussion distribution, since the VAE forces it to follow the gaussian distribution. Sampling ligands from gaussian distribution (prior) should work, I think. 
But what is the reason that the validity ratio is 0% by sampling ligands from gaussian distribution (prior) then  concatenated it with encoded receptor vector, and then decode to molecules?  Please help confirm if my understanding is correct. sorry for asking so many questions.

**Comment by yangxiufengsia** [comment]
Hi,
Thank you for previous discussion. I would like to confirm another one thing: according to our above discussion, it seems reducing L2 loss is more important than KL loss. Is that one reason that a much larger weight was assigned for GAN loss and L2 loss? do you want to reduce L2 loss faster than KL loss ?
Looking forward to discussing with you further!

**Comment by yangxiufengsia** [comment]
I understand finally, so I close the issue. Thanks
