### ISSUE TITLE
why 1024-D latent space?

### ISSUE THREAD

**Issue by yangxiufengsia** [mattragoza/liGAN#18]
Hi,

Why choosing 1024-dimensional latent space? did you try other dimensions?

Thank you.

**Comment by mattragoza** [comment]
We trained models with 512, 1024, and 2048-dimensional latent spaces in our earlier model optimization experiments, and we selected 1024 because it had the best tradeoff between reconstruction loss and computational cost.

**Comment by yangxiufengsia** [comment]
Thanks a lot for your answer. I tried to reduce the latent dimension to lower ones (like 64). But the reconstruction loss seems can not be reduced further. Do you know why the latent dimension can not be reduced? Is that because of the grid density definition? Do you have any suggestions? Thank you. Looking forward to your answers.

**Comment by mattragoza** [comment]
I would not be surprised to find that beyond a certain lower bound, the reconstruction performance starts to suffer- if the latent space is smaller than the size of the data manifold, there will be loss of information in the latent representation.

However, the relationship between reconstruction ability and latent space size in VAEs is not always straightforward, due to the probabilistic nature of the model. If it learns to encode inputs with tighter variance, it can represent more information in the same space than a model with higher encoder variance. This comes down to an interplay between the reconstruction loss and the K-L divergence loss.

In our recent experiments (using the refactor branch, with pytorch and other model improvements) we have actually seen better reconstruction ability using a latent space of size 128 compared to the previous models that used 1024. The most significant improvements in reconstruction ability have come from increasing the reconstruction loss weight and decreasing the K-L divergence weight, but this comes at the cost of increased difficulty sampling useful regions of the latent space when generating prior samples.

**Comment by yangxiufengsia** [comment]
thanks a lot for your comments. Have you tried much lower dimensions than 128D? How was the performance? By the way, why the training cost so long time?
