### ISSUE TITLE
MemoryError at molgrid.ExampleProvider().next_batch()

### ISSUE THREAD

**Issue by wxfsd** [mattragoza/LiGAN#30]
Hi. 
First , I get the error (Segmentation fault (core dumped)),  so I manually installing libmolgrid, and I solved this problem.

After, I get the MemoryError in molgrid.ExampleProvider().next_batch().   [/liGAN/data.py(139 line)] The code just froze at next_batch under libmolgrid library. At this time, my batch_size and n_examples have been set to 1.

This is my server configuration. Mem is 377G, Swp is 7.63G and 10018MiB GPU memory(GeForce RTX 3080).
![image](https://user-images.githubusercontent.com/39430262/147095791-75ea7e53-664c-4986-8911-3131580ef2af.png)

I find this grid dimensions is 48, I don't know how much memory we need to run. I don’t know if it’s the memory problem of my server or the problem of the molgrid package. 

Please tell me the configuration of the server required for testing. 

Looking forward to your help! Thank you very munch!

**Comment by mattragoza** [comment]
The problem is likely not due to your available memory, which should be sufficient for the provided model and config. There is a known issue that we are working to resolve where there are incompatible molgrid and openbabel versions. It likely has to do with a mismatch between the conda installed openbabel and molgrid. When you built molgrid from source, did you check to make sure it was built with the openbabel you expect (i.e. check to make sure there are not multiple copies installed on your system)?
