### ISSUE TITLE
How I can use pre-trained model to generate new chemistry with my pdb file (protein+ligand)

### ISSUE THREAD

**Issue by sll513** [mattragoza/liGAN#40]
Thanks,

**Comment by INHYEOKSONG** [comment]
editing generate.config file , 
Currently, that's how I'm creating it.

**Comment by mattragoza** [comment]
You should create a new data file (refer to `data/it2_tt_0_lowrmsd_valid_mols_test0_1000.types` for an example) that references the structure files you want to use. Then you should copy/edit `config/generate.config` so that the `data_file` setting refers to your new data file and the `data_root` setting is correctly set as well. Then run `python generate.py generate.config`.

To create a new data file, the receptor and input ligand should first be split into separate files, and the ligand should be split into separate files for each pose. Then you should put them in the data file with the row format "{class_label:d} {affinity:f} {RMSD:f} {receptor_path} {ligand_path}". The only two relevant columns are receptor_path and ligand_path, which should be paths to the structure file relative to the data_root variable. I.e. if you have a structure file at `/users/me/data/rec1/rec1.pdb` and your data file contains a reference to `rec1/rec1.pdb` then you should data_root to /`users/me/data`.
